const STORAGE_KEY = "antesqueeuesqueca.editorial.v1";
const QA_ITEMS = ["Scroll completo sem travar","Proporções e enquadramentos","Prévia mobile","Prévia desktop","Home e arquivo atualizados","Links e embeds funcionando","Fallback para mídia externa","Analytics G-EP2SKWWE0S preservado","Título e descrição da página","Imagem e texto de compartilhamento"];

const blankSuggestion = () => ({id:crypto.randomUUID(),achado:"",tipo:"",descricao:"",motivo:"",conexao:"",editoria:"Bonitezas",tempo:"",fontes:"",status:"pending",pesquisa:"",fatos:"",limites:"",abordagem:""});
const blankBlock = () => ({id:crypto.randomUUID(),titulo:"",funcao:"",ideia:"",midia:"texto",proporcao:"",origem:"",fallback:"",texto:"",imagemNome:"",imagemUrl:"",legenda:"",credito:""});
const initialState = () => ({version:1,updatedAt:new Date().toISOString(),meta:{title:"",editoria:"Bonitezas",intencao:""},suggestions:[blankSuggestion()],blocks:[],qa:Object.fromEntries(QA_ITEMS.map(x=>[x,false]))});
let state = load();

function load(){try{return {...initialState(),...JSON.parse(localStorage.getItem(STORAGE_KEY))}}catch{return initialState()}}
function save(){state.updatedAt=new Date().toISOString();const persisted=JSON.parse(JSON.stringify(state));persisted.blocks.forEach(b=>delete b.imagemUrl);localStorage.setItem(STORAGE_KEY,JSON.stringify(persisted));const el=document.querySelector("#save-state");el.textContent="salvo agora neste navegador";clearTimeout(save.timer);save.timer=setTimeout(()=>el.textContent="salvo neste navegador",1300)}
function esc(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function field(label,key,value="",type="input",extra=""){const tag=type==="textarea"?`<textarea data-key="${key}" ${extra}>${esc(value)}</textarea>`:type==="select"?`<select data-key="${key}" ${extra}>${value}</select>`:`<input data-key="${key}" value="${esc(value)}" ${extra}>`;return `<div><label>${label}</label>${tag}</div>`}
function empty(text){return `<div class="empty"><b>Nada aqui ainda.</b><span>${text}</span></div>`}

function bindMeta(){document.querySelectorAll("[data-field]").forEach(el=>{const key=el.dataset.field.split(".")[1];el.value=state.meta[key]||"";el.addEventListener("input",()=>{state.meta[key]=el.value;save();if(document.querySelector('[data-panel="previa"]').classList.contains("active"))renderPreview()})})}
function renderSuggestions(){const root=document.querySelector("#suggestions");root.innerHTML=state.suggestions.length?state.suggestions.map((s,i)=>`<article class="item-card" data-suggestion="${s.id}"><div class="item-top"><h3>Sugestão ${String(i+1).padStart(2,"0")}</h3><button class="icon-button" data-remove-suggestion="${s.id}" aria-label="Remover">remover</button></div><div class="field-grid">${field("Achado","achado",s.achado)}${field("Tipo","tipo",s.tipo)}${field("O que é","descricao",s.descricao,"textarea",'rows="3" class="full"')}${field("Por que entrou no radar","motivo",s.motivo,"textarea",'rows="3"')}${field("Conexão possível","conexao",s.conexao,"textarea",'rows="3"')}${field("Editoria provisória","editoria",`<option ${s.editoria==="Bonitezas"?"selected":""}>Bonitezas</option><option ${s.editoria==="Reencontros"?"selected":""}>Reencontros</option>`,"select")}${field("Tempo para explorar","tempo",s.tempo)}${field("Fontes / links","fontes",s.fontes,"textarea",'rows="2" class="full"')}</div><div class="choice-row"><button class="choice ${s.status==="approved"?"selected":""}" data-action="approve">aprovar</button><button class="choice ${s.status==="saved"?"selected":""}" data-action="save">guardar</button><button class="choice ${s.status==="discarded"?"selected":""}" data-action="discard">descartar</button></div></article>`).join(""):empty("Adicione até cinco sugestões.");bindCards("suggestion")}
function bindCards(kind){const attr=kind==="suggestion"?"data-suggestion":"data-block";document.querySelectorAll(`[${attr}]`).forEach(card=>{const id=card.getAttribute(attr);const list=kind==="suggestion"?state.suggestions:state.blocks;const item=list.find(x=>x.id===id);card.querySelectorAll("[data-key]").forEach(el=>el.addEventListener("input",()=>{item[el.dataset.key]=el.value;save()}));card.querySelectorAll("[data-action]").forEach(btn=>btn.addEventListener("click",()=>{item.status={approve:"approved",save:"saved",discard:"discarded"}[btn.dataset.action];save();renderSuggestions();renderResearch()}))})}
function renderResearch(){const approved=state.suggestions.filter(s=>s.status==="approved");const root=document.querySelector("#research");root.innerHTML=approved.length?approved.map(s=>`<article class="item-card" data-suggestion="${s.id}"><div class="item-top"><h3>${esc(s.achado||"Sugestão aprovada")}</h3><span class="status">aprovada</span></div><div class="field-grid">${field("Pesquisa e contexto","pesquisa",s.pesquisa,"textarea",'rows="5" class="full"')}${field("Fatos confirmados","fatos",s.fatos,"textarea",'rows="4"')}${field("Direitos, acesso e limites","limites",s.limites,"textarea",'rows="4"')}${field("Possibilidades de abordagem","abordagem",s.abordagem,"textarea",'rows="4" class="full"')}</div></article>`).join(""):empty("Aprove uma sugestão no Radar para começar a pesquisa.");bindCards("suggestion")}
function blockSelect(b){return `<option value="texto" ${b.midia==="texto"?"selected":""}>Texto</option><option value="imagem" ${b.midia==="imagem"?"selected":""}>Imagem</option><option value="video" ${b.midia==="video"?"selected":""}>Vídeo / embed</option><option value="playlist" ${b.midia==="playlist"?"selected":""}>Playlist</option><option value="link" ${b.midia==="link"?"selected":""}>Link para explorar</option>`}
function renderArchitecture(){const root=document.querySelector("#architecture");root.innerHTML=state.blocks.length?state.blocks.map((b,i)=>`<article class="item-card" data-block="${b.id}"><div class="item-top"><h3>Bloco ${String(i+1).padStart(2,"0")}</h3><button class="icon-button" data-remove-block="${b.id}">remover</button></div><div class="field-grid">${field("Título provisório","titulo",b.titulo)}${field("Função na edição","funcao",b.funcao)}${field("Ideia do bloco","ideia",b.ideia,"textarea",'rows="3" class="full"')}${field("Tipo de mídia","midia",blockSelect(b),"select")}${field("Proporção recomendada","proporcao",b.proporcao)}${field("Origem da imagem / mídia","origem",b.origem)}${field("Embed ou fallback","fallback",b.fallback)}</div></article>`).join(""):empty("Adicione os blocos depois de aprovar a arquitetura da edição.");bindCards("block")}
function renderWriting(){const root=document.querySelector("#writing");root.innerHTML=state.blocks.length?state.blocks.map((b,i)=>`<article class="item-card" data-block="${b.id}"><div class="item-top"><h3>${esc(b.titulo||`Bloco ${i+1}`)}</h3><span class="status">${esc(b.funcao||"função pendente")}</span></div>${field("Texto final do bloco","texto",b.texto,"textarea",'rows="10"')}</article>`).join(""):empty("A escrita será liberada quando a arquitetura tiver blocos.");bindCards("block")}
function renderImages(){const root=document.querySelector("#images");root.innerHTML=state.blocks.length?state.blocks.map((b,i)=>`<article class="item-card" data-block="${b.id}"><div class="item-top"><h3>${esc(b.titulo||`Bloco ${i+1}`)}</h3><span class="status">${esc(b.midia)}</span></div><div class="image-zone"><div class="image-preview">${b.imagemUrl?`<img src="${b.imagemUrl}" alt="Prévia">`:"nenhuma imagem escolhida"}</div><div class="field-grid"><div class="full"><label>Arquivo para prévia</label><input type="file" accept="image/*" data-image-file></div>${field("Nome final do arquivo","imagemNome",b.imagemNome)}${field("Proporção","proporcao",b.proporcao)}${field("Legenda","legenda",b.legenda)}${field("Crédito","credito",b.credito)}</div></div></article>`).join(""):empty("Crie os blocos da edição antes de selecionar imagens.");bindCards("block");root.querySelectorAll("[data-image-file]").forEach(input=>input.addEventListener("change",()=>{const card=input.closest("[data-block]");const b=state.blocks.find(x=>x.id===card.dataset.block);const file=input.files[0];if(!file)return;b.imagemNome=b.imagemNome||file.name;b.imagemUrl=URL.createObjectURL(file);save();renderImages()}))}
function renderQA(){const root=document.querySelector("#qa-list");root.innerHTML=QA_ITEMS.map(item=>`<label class="qa-item"><input type="checkbox" ${state.qa[item]?"checked":""} data-qa="${esc(item)}"><span>${esc(item)}</span></label>`).join("");root.querySelectorAll("[data-qa]").forEach(el=>el.addEventListener("change",()=>{state.qa[el.dataset.qa]=el.checked;save()}))}

function previewDocument(){const blocks=state.blocks.map((b,i)=>`<section><p class="number">${String(i+1).padStart(2,"0")}</p><h2>${esc(b.titulo||"Bloco sem título")}</h2>${b.imagemUrl?`<figure><img src="${b.imagemUrl}" alt="${esc(b.legenda)}"><figcaption>${esc(b.legenda)}${b.credito?` · ${esc(b.credito)}`:""}</figcaption></figure>`:""}${(b.texto||b.ideia)?String(b.texto||b.ideia).split(/\n+/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join(""):"<p class='pending'>Texto pendente.</p>"}</section>`).join("");return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>:root{--paper:#f4ebdd;--ink:#25263a;--blush:#e36888;--line:rgba(37,38,58,.17)}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Arial,sans-serif;line-height:1.65}header,main{width:min(760px,calc(100% - 32px));margin:auto}header{padding:46px 0 30px;border-bottom:1px solid var(--line)}.brand{font-family:monospace;font-weight:bold}.brand span,.number{color:var(--blush)}h1,h2{font-family:Georgia,serif}h1{font-size:clamp(2rem,6vw,4rem);line-height:1.05}header p{max-width:580px}section{padding:40px 0;border-bottom:1px solid var(--line)}section h2{margin:0 0 16px;font-size:2rem}section>p:not(.number){font-size:1.05rem}.number{font-family:monospace}figure{margin:22px 0}img{display:block;width:100%;max-height:520px;object-fit:cover}figcaption{margin-top:6px;font-size:.72rem;color:#696573}.pending{color:#696573;font-style:italic}@media(max-width:520px){header{padding-top:28px}section{padding:28px 0}section h2{font-size:1.55rem}}</style></head><body><header><div class="brand"><span>✳</span> antes que eu esqueça.</div><p>${esc(state.meta.editoria)}</p><h1>${esc(state.meta.title||"Edição sem título")}</h1><p>${esc(state.meta.intencao||"Intenção editorial pendente.")}</p></header><main>${blocks||"<section><p class='pending'>A prévia aparece quando a arquitetura tiver blocos.</p></section>"}</main></body></html>`}
function renderPreview(){document.querySelector("#preview-frame").srcdoc=previewDocument()}
function showPanel(name){document.querySelectorAll(".panel").forEach(p=>p.classList.toggle("active",p.dataset.panel===name));document.querySelectorAll(".step").forEach(p=>p.classList.toggle("active",p.dataset.step===name));({radar:renderSuggestions,pesquisa:renderResearch,arquitetura:renderArchitecture,escrita:renderWriting,imagens:renderImages,previa:renderPreview,qa:renderQA}[name])()}
function exportProject(){const safe=JSON.parse(JSON.stringify(state));safe.blocks.forEach(b=>delete b.imagemUrl);const blob=new Blob([JSON.stringify(safe,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${(state.meta.title||"nova-edicao").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}.json`;a.click();URL.revokeObjectURL(a.href)}
function importProject(file){const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result);state={...initialState(),...parsed};save();bindMeta();showPanel("radar")}catch{alert("Não consegui abrir este projeto. Confira se o arquivo é JSON.")}};reader.readAsText(file)}

document.querySelectorAll(".step").forEach(btn=>btn.addEventListener("click",()=>showPanel(btn.dataset.step)));
document.querySelector("#add-suggestion").addEventListener("click",()=>{if(state.suggestions.length>=5)return alert("O Radar trabalha com até cinco sugestões por vez.");state.suggestions.push(blankSuggestion());save();renderSuggestions()});
document.querySelector("#add-block").addEventListener("click",()=>{state.blocks.push(blankBlock());save();renderArchitecture()});
document.addEventListener("click",e=>{if(e.target.dataset.removeSuggestion){state.suggestions=state.suggestions.filter(x=>x.id!==e.target.dataset.removeSuggestion);save();renderSuggestions();renderResearch()}if(e.target.dataset.removeBlock){state.blocks=state.blocks.filter(x=>x.id!==e.target.dataset.removeBlock);save();renderArchitecture()}});
document.querySelectorAll("#export-project,#export-project-qa").forEach(btn=>btn.addEventListener("click",exportProject));
document.querySelector("#import-file").addEventListener("change",e=>e.target.files[0]&&importProject(e.target.files[0]));
document.querySelectorAll("[data-device]").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("[data-device]").forEach(x=>x.classList.toggle("active",x===btn));document.querySelector("#preview-shell").className=`preview-shell ${btn.dataset.device}`}));
bindMeta();renderSuggestions();
